version = 1

exclude_patterns = [
    "/dist/*.js",
    "/vendor/*"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "browser",
    "jquery"
  ]
  style_guide = "airbnb"
